#!/usr/bin/env node
/**
 * Prebuild script: fetch blog posts from admin API and save as generated data
 * Runs before `next build` to keep blog content up to date.
 */
import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ADMIN_API = process.env.ADMIN_API_URL || "https://admin.rimhappywoods.top";
const API_URL = `${ADMIN_API}/api/blog?include=content`;
const OUTPUT = path.resolve(__dirname, "..", "src/data/generated/blog-data.ts");

function fetchJson(url) {
  const out = execSync(`curl -sf "${url}"`, {
    encoding: "utf-8",
    timeout: 15000,
    env: { ...process.env },
  });
  return JSON.parse(out);
}

async function main() {
  console.log("📝 Fetching blog posts from admin API...");
  console.log(`   ${API_URL}`);

  const posts = fetchJson(API_URL);

  const mapped = posts
    .filter((p) => p.published && p.slug)
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      excerpt: p.excerpt || "",
      content: p.content || "",
      image: p.image_key
        ? "/images/" + p.image_key
        : "/images/imgs/blogImgs/default.jpg",
      date: (p.published_at || p.created_at || "").split("T")[0],
      author: p.author || "Yazhong Team",
      category: p.category || "General",
      tags: [],
    }));

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });

  const tsContent = `// Auto-generated by scripts/fetch-blog.mjs — DO NOT EDIT
import type { BlogPost } from "@/types";

export const generatedBlogPosts: BlogPost[] = ${JSON.stringify(mapped, null, 2)};

export const generatedBlogCategories: string[] = ["All", ...new Set(${JSON.stringify(mapped.map((p) => p.category))})];
`;
  fs.writeFileSync(OUTPUT, tsContent);

  console.log(`✅ ${mapped.length} blog posts saved to src/data/generated/`);
}

main().catch((err) => {
  console.error("❌ Failed to fetch blog posts:", err.message);
  process.exit(0);
});
