#!/usr/bin/env node
/**
 * Prebuild script: fetch blog posts from admin API and save as generated data.
 * Runs before `next build` to keep blog content up to date.
 *
 * Uses native fetch (Node 24+) with cache fallback: if the API is
 * unreachable, reuses the previously written generated file so deploys
 * keep working through transient outages. Fails loudly (exit 1) only on
 * the first build when no cache exists.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { fetchJsonWithFallback } from "./lib/fetch-with-fallback.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ADMIN_API = process.env.ADMIN_API_URL || "https://admin.rimhappywoods.top";
const API_URL = `${ADMIN_API}/api/blog?include=content`;
const OUT_DIR = path.resolve(__dirname, "..", "src/data/generated");
const BLOG_TS = path.resolve(OUT_DIR, "blog-data.ts");
// Cache the raw API JSON separately so fallback can restore it on next run.
const BLOG_CACHE = path.resolve(OUT_DIR, "blog-raw.json");

async function main() {
  console.log("📝 Fetching blog posts from admin API...");
  console.log(`   ${API_URL}`);

  const posts = await fetchJsonWithFallback(API_URL, {
    cachePath: BLOG_CACHE,
    label: "blog posts",
  });

  const mapped = posts
    .filter((p) => p.published && p.slug)
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      excerpt: p.excerpt || "",
      content: p.content || "",
      image: p.image_key
        ? "/images/" + p.image_key
        : "/images/imgs/blogImgs/default.jpg",
      date: (p.published_at || p.created_at || "").split("T")[0],
      author: p.author || "Yazhong Team",
      category: p.category || "General",
      tags: [],
    }));

  fs.mkdirSync(OUT_DIR, { recursive: true });

  const tsContent = `// Auto-generated by scripts/fetch-blog.mjs — DO NOT EDIT
import type { BlogPost } from "@/types";

export const generatedBlogPosts: BlogPost[] = ${JSON.stringify(mapped, null, 2)};

export const generatedBlogCategories: string[] = ["All", ...new Set(${JSON.stringify(mapped.map((p) => p.category))})];
`;
  fs.writeFileSync(BLOG_TS, tsContent);

  console.log(`✅ ${mapped.length} blog posts saved to src/data/generated/`);
}

main().catch((err) => {
  console.error("❌ Failed to fetch blog posts:", err.message);
  console.error("   No cached fallback available. Build cannot proceed safely.");
  process.exit(1);
});
